modified code
PritiSah6299/todo pull request #1
Opened 2024-01-31 10:20 UTC by PritiSah6299

Cleaned and modified code.

2024-02-01 13:32 UTC, kbirulia requested changes
Great job!

2024-02-01 13:32 UTC, kbirulia commented on src/App.js
>      const [filter, setFilter] = useState('all');
Would be nice to have constants for filter values

2024-02-01 13:32 UTC, kbirulia commented on src/App.js
> +    const filterTodos= useMemo(()=> {return todos.filter(todo => {
For performance reason is better to filter separetly for each filter (all is not needed to be filtered)

2024-02-01 13:32 UTC, kbirulia commented on src/App.js
>    const inpst={
Use styled components outside of component

2024-02-01 13:32 UTC, kbirulia commented on src/App.js
>    await dispatch({type:'update',payload: event.target.value});
Would be nice to have constants for types

2024-02-01 13:32 UTC, kbirulia commented on src/App.js
onToggle is not dispatch. Keep, please, naming meaningful

2024-02-05 05:15 UTC, PritiSah6299 commented
Need to add a delete feature for list.

2024-02-05 05:16 UTC, merged